# Generated by Django 3.0.1 on 2019-12-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('day', models.DateField()),
                ('mobile', models.IntegerField()),
                ('land', models.IntegerField()),
                ('Mild', models.IntegerField(default=0)),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('DateofGrant', models.DateField()),
                ('PRP', models.IntegerField()),
                ('Mineralname', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('GrantedArea', models.IntegerField()),
                ('DateofAuction', models.DateField()),
                ('HighestBid', models.IntegerField()),
                ('NoofInstallments', models.IntegerField()),
                ('DueDate', models.DateField()),
                ('AmountofInstallments', models.IntegerField()),
            ],
        ),
    ]
